### ISSUE TITLE
couldn't run

### ISSUE THREAD

**Issue by zx0922** [meganz/iOS3#25]
/Users/Username/Library/Developer/Xcode/DerivedData/iMEGA-cujkiledemedyedehlqqbgtyblhh/Build/Intermediates/MEGA.build/Debug-iphoneos/MEGA.build/Script-41BF6BE71D82D93100330785.sh: line 3: ./create_bundle.sh: No such file or directory

I have done this step:
4.- Uncompress that file and move the folders include and lib into iMEGA/Vendor/sdk/bindings/ios/3rdparty

**Comment by jnavarrom** [comment]
Hi,
I followed all the steps in the readme and it worked for me.

Maybe, you missed this step `git submodule update --init --recursive`
Did you run `git submodule update --init --recursive`?

**Comment by jnavarrom** [comment]
Closed due to inactivity
