### ISSUE TITLE
Connection problems

### ISSUE THREAD

**Issue by ECer23** [meganz/iOS3#31]
I can't connect to MEGA in my iPhone(iOS11) through wifi. But I can use it through 4G connections
And in PC/Mac client, I have to use VPN to log in, but the file sync can run without a VPN connection
I'm a student in China, so the reason might be the GFW or my campus wifi. But it's weird that I can use it through 4G. Could anyone solve my problem?

**Comment by jnavarrom** [comment]
We are aware that there are DNS issues in some cities in the mainland China. The Chinese ISPs are too powerful to be challenged, yet we stand by privacy and safety overweight anything else. Therefore, you have to use the VPN.

Sorry, but I don't think that we can do nothing.
