### ISSUE TITLE
splash screen won't go away.

### ISSUE THREAD

**Issue by fdisp** [meganz/iOS3#32]
## General Information

* about 1.6 GB offline files stored in the device.
* debugging mode: active, since a previous version was uploading
twice or more times the same photos in the camera uploads folder (in cloud).
the debug log is about 140 MB large and the data for this problem are supposed to be located at the end of the log.
DEBUG LOG: https://mega.nz/#!dw5URYyL!aNb7sl4W2j0c8n9HoEPmRKOLZNCgn0dfq6bUuG7j924

* MEGA Version: 3.8.6
* iOS Version(s): 11.3
* Device: iphone 6
* Reproducible?: possibly. to increase the chance of reproducing, 
**close iOS app, 
connect megasync client in another pc and login with the same account that the mobile device is set,
both the pc and the iDevice must be connected within the same network.
switching to mobile data the mega app gui shows up as usual.
switching back again to wireless (the same network as another megasync client) the app stays in splash screen.**

##  What happened?
tap on mega app in iOS will open the splash screen.
the splash screen stays there forever with it's "loading" animation rotating (not frozen).
SPLASH SCREEN: https://mega.nz/#!RoJxTJJR!YdLZfXZ39Jq-cOvB46nxRgMqe6Mb5RoKlz9wwqW-GsE
the app gui won't show anytime soon.

## What did you expect to happen?
it is expected that the splash screen will stay there for a few seconds and then the app's gui is supposed to show up for the user to interact with.

**Comment by jnavarrom** [comment]
Hi, thank you for your feedback and for the log. 

In the log, there are some issues resolving the DNS:

> Resolving IPv4 address for g.api.mega.co.nz (net.cpp:1675)
> c-ares info received (net.cpp:971)
> c-ares error. code: 12 (net.cpp:1018)
> Unable to get the IP for g.api.mega.co.nz (net.cpp:1053)
> Error in c-ares. Reinitializing... (net.cpp:1554)
> c-ares info received (net.cpp:971)
> c-ares error. code: 16 (net.cpp:1018)
> Request cancelled (net.cpp:1029)
> Using custom DNS servers: 192.168.1.9,192.168.1.10,192.168.1.12 (net.cpp:1563)

Are you using WiFi or Mobile Data?
If you are using WiFi, please can you check how do you have configured the DNS (Settings --> WiFi--> select (i) for the WiFi you are connected to --> Go to DNS section)?

Can you reproduce the same issue using Mobile Data?

**Comment by fdisp** [comment]
looks like the cause of this issue were several offline DNS servers (like the pihole ad  in my local network which were supposed to be online. in the list of manually configured DNS servers there was also an online DNS server which i'm guessing was the reason why other applications and browsers in my device were working fine.
by removing the offline DNS servers in the WIFI section in iOS, the issue was resolved.
since the source of the problem were the manually configured offline DNS servers in the WIFI section, it can not be reproduced using mobile data. 
thanks!
