### ISSUE TITLE
Unable to save to Mega from Safari

### ISSUE THREAD

**Issue by pasques** [meganz/iOS3#33]
## General Information

* MEGA Version: 3.8.8

* iOS Version(s): 11.3

* Devices/Simulators: iPad mini 4

* Reproducible? (Yes/No): yes

##  What happened?
In Safari, Goto to https://en.m.wikipedia.org/wiki/File:Hurricane_Carmen_1974_satellite.jpg
Click the graphic, and it will go from the webpage to just the graphic.
Tap the square with the up arrow (there’s a name for that icon, isn’t there?) on the top right side.
Find Mega (red square with M) and tap.
Mega opens for a second and then shuts down going back to safari.

## What did you expect to happen?
The ability to save the graphic to Mega.

**Comment by jnavarrom** [comment]
Hi,

The problem is that the URL you are trying to upload is not an image, it is a HTML.
Select one image: for example 728 x 600 pixels, safari will open this URL which is an image and then you can upload the image using MEGA. https://upload.wikimedia.org/wikipedia/commons/thumb/0/06/Hurricane_Carmen_1974_satellite.jpg/728px-Hurricane_Carmen_1974_satellite.jpg

Regards

**Comment by pasques** [comment]
Sorry I'm direct, but my link is not HTML. It's an image just like yours. In my second step above, I said click the graphic and it will go to just the graphic. Safari goes to https://upload.wikimedia.org/wikipedia/commons/0/06/Hurricane_Carmen_1974_satellite.jpg 

I tried your link as well and I get the same result. 

For now, as a work around I can just save to Photos and use Camera Uploads.

**Comment by jnavarrom** [comment]
This URL
https://upload.wikimedia.org/wikipedia/commons/0/06/Hurricane_Carmen_1974_satellite.jpg

is not the same as this URL: https://en.m.wikipedia.org/wiki/File:Hurricane_Carmen_1974_satellite.jpg

With this https://upload.wikimedia.org/wikipedia/commons/0/06/Hurricane_Carmen_1974_satellite.jpg
the app upload the image.

![upload_image_from_url](https://user-images.githubusercontent.com/3861964/40008014-9595070c-579e-11e8-8285-f03dbed763e7.gif)
